### ISSUE TITLE
Fedora 39 javascript error

### ISSUE THREAD

**Issue by RobusTetus** [gicmo/gamemode-extension#72] opened 2023-11-07 23:22 UTC
Upon turning on the extension through the GNOME Extensions app, error message shows up reading "import declarations may only appear at top level of a module".

The settings of extension gamemode@christian.kellner.me had an error:
```
SyntaxError: import declarations may only appear at top level of a module
```

Stack trace:
```
@file:///usr/share/gnome-shell/extensions/gamemode@christian.kellner.me/prefs.js:1:24
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by fjsevilla-dev** [comment] 2023-11-08 23:15
Hi @RobusTetus, Fedora 39 uses GNOME 45 which has brought important changes regarding extensions, the main one being that GNOME Shell 45 moved to ESM (which is the reason for the error you mention). 

The version available in extensions.gnome.org is not compatible with Gnome 45, and, unlike previous versions, adding the new version to metadata.json or disabling compatibility checking is not enough. To make the extension compatible with GNOME 45 we have to make code changes that break backwards compatibility.

There is an open issue about this topic; [GNOME 45 support](https://github.com/gicmo/gamemode-extension/issues/70). If you want to use the extension on Fedora 39, you can build from source and install the port  to GNOME 45 in my fork, until Gicmo can update the extension to a newer version. [See my comment on this issue](https://github.com/gicmo/gamemode-extension/issues/70#issuecomment-1693012851
) to see how to do it.

If you have any problems let me know.

**Comment by fjsevilla-dev** [comment] 2023-11-08 23:17
Duplicate of #70

**Closed as not planned by fjsevilla-dev** 2023-11-08 23:17 UTC
